### ISSUE TITLE
Could you provide a trained model for testing?

### ISSUE THREAD

**Issue by lz2470** [znxlwm/UGATIT-pytorch#1]
Hi, Thank you for sharing this great project. Would you mind sharing a trained model for me to test？ Or data set for training? Thx in advance

**Comment by TheDukeZip** [comment]
I think many of us would love this if possible. I noticed they were still committing things so I've been keeping on eye on the repo

**Comment by znxlwm** [comment]
We will soon release pre-trained tensorflow model (https://github.com/taki0112/UGATIT) and selfi2anime dataset.

There are no plans to release pytorch models yet.
