### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ResnetGenerator

### ISSUE THREAD

**Issue by codecrack3** [znxlwm/UGATIT-pytorch#16]
![image](https://user-images.githubusercontent.com/9525576/62672651-c5382e00-b9c5-11e9-8aba-1159bbbff142.png)

When I pull new code in the repository I could not pretrain my model. I catch a exception

**Comment by WynMew** [comment]
@codecrack3 

The repo has been updated a few years ago. And the network has been revised.
