### ISSUE TITLE
Can anyone tell me how to run it?

### ISSUE THREAD

**Issue by IMakiMaki** [znxlwm/UGATIT-pytorch#27]
I've never write python code.So how can I run it? 
I try to run `python main.py --dataset selfie2anime` in cmd.But some errors be displayed:
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from UGATIT import UGATIT
  File "/Users/yh/Personal/UGATIT-pytorch/UGATIT.py", line 2, in <module>
    from dataset import ImageFolder
  File "/Users/yh/Personal/UGATIT-pytorch/dataset.py", line 1, in <module>
    import torch.utils.data as data
ImportError: No module named torch.utils.data`

**Comment by kezif** [comment]
You should install all required libs. 
Also this project is pretty bad as first python script. There is no pretrained weights, so you should train network by yourself (create dataset and train it for like eons)

**Comment by IMakiMaki** [comment]
emm...OK..... Maybe I should try another project.Thank you so much.
