### ISSUE TITLE
light flag is not working?

### ISSUE THREAD

**Issue by JeffSaa** [znxlwm/UGATIT-pytorch#3]
I ran `python main.py --dataset selfie2anime --light True` but I have this error

`AssertionError: Torch not compiled with CUDA enabled`

**Comment by znxlwm** [comment]
Hi,

`--light` flag means a low gpu memory usage setting, not cpu.

if you want to cpu mode, use `--device 'cpu'`

Thank you

**Comment by JeffSaa** [comment]
Great! Thanks
