### ISSUE TITLE
Wrong Instance/Layer norm evaluation

### ISSUE THREAD

**Issue by kefirski** [znxlwm/UGATIT-pytorch#30]
It seems like your implementation of AdaILN/ILN layer in pytorch significantly differs from tf version (actually, tf version is the correct one).

```
in_mean, in_var = torch.mean(torch.mean(input, dim=2, keepdim=True), dim=3, keepdim=True), torch.var(torch.var(input, dim=2, keepdim=True), dim=3, keepdim=True)
ln_mean, ln_var = torch.mean(torch.mean(torch.mean(input, dim=1, keepdim=True), dim=2, keepdim=True), dim=3, keepdim=True), torch.var(torch.var(torch.var(input, dim=1, keepdim=True), dim=2, keepdim=True), dim=3, keepdim=True)
```

This block implies that when you are trying to evaluate variance of each tensor in the batch over appropriate dimension, instead of variation over axes `[2, 3]` in IN and axes `[1, 2, 3]` in LN you evaluate variation of variation in IN and variation of variation of variation in LN which is wrong

**Comment by znxlwm** [comment]
Thanks!
