### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by ElecRex** [znxlwm/UGATIT-pytorch#7]
Hi, thanks for this incredible net.  I've already trained the dataset, but when I aim to test it and
I input the following command:  ```python main.py --phrase test --light true```
However, I got the error in the log:
```
##### Information #####
# light :  True
# dataset :  selﬁe2anime
# batch_size :  1
# iteration per epoch :  1000000

##### Generator #####
# residual blocks :  4

##### Discriminator #####
# discriminator layer :  6

##### Weight #####
# adv_weight :  1
# cycle_weight :  10
# identity_weight :  10
# cam_weight :  1000
 [*] Load FAILURE
 [*] Test finished!
```

**Comment by znxlwm** [comment]
Above error occurred in the following code in my guess:

```
    def test(self):
        model_list = glob(os.path.join(self.result_dir, self.dataset, 'model', '*.pt'))
        if not len(model_list) == 0:
            model_list.sort()
            iter = int(model_list[-1].split('_')[-1].split('.')[0])
            self.load(os.path.join(self.result_dir, self.dataset, 'model'), iter)
            print(" [*] Load SUCCESS")
        else:
            print(" [*] Load FAILURE")
            return
```

It works well for me. I'm sorry, I don't know why you got the error...
Debug the code above.

Thank you

**Comment by ElecRex** [comment]
Thanks, I wanna know if the model folder under the results directory is empty after training

**Comment by Trueyellow** [comment]
The state dict of model is saved to the `model` folder every 100k iterations by default. Make sure you have reached that point.

**Comment by youyouhdhd** [comment]
Did you solve it? I also met the same problem.

**Comment by ElecRex** [comment]
@youyouhdhd 
Not yet.

**Comment by nameCody** [comment]
You need to put the pretrained model to results/selfie2anime/model/
