### ISSUE TITLE
Why does the training batchsize default to 1?

### ISSUE THREAD

**Issue by chaipangpang** [znxlwm/UGATIT-pytorch#8]
Hi, Thank you for release this project. Why does the training batchsize default to 1? Can it be a larger value?

**Comment by znxlwm** [comment]
Hi,

First, many previous works, (e.g., Cycle GAN, MUNIT etc.), used training batch size as 1.
Second, our model needs a lot of GPU memory.

So,,, we used batch size as 1.

**Comment by chaipangpang** [comment]
If multi-GPU training is used, can the number of iterations be reduced accordingly?
